### ISSUE TITLE
Input ASE data for ANEVA-DOT

### ISSUE THREAD

**Issue by MariaEliana** [PejLab/ANEVA-DOT#6]
Hallo @pejminister !

Thank you for developing and sharing these useful packages! We are very new in this field, so we started by following your tutorial ( https://stephanecastel.wordpress.com/2017/02/15/how-to-generate-ase-data-with-phaser/) . We performed both phaser and phaser_gene_ae and they worked great, but once obtained all the output files, we didn’t understand which one should be used as input for ANEVADOT, since they look differently than the sample_ASE data you shown here [https://rdrr.io/github/PejLab/ANEVA-DOT/man/sample_ASE.html](url) . There are other intermediate steps that we are missing? 

Thanks in advance.

**Comment by wickdChromosome** [comment]
Hello @MariaEliana,

Thanks for your interest in our work! 
At the moment, ANEVA-DOT can not be used with haplotype level data from phaser, but phaser also outputs variant level data (in the files ending with "alleic_counts.txt") which should work fine - these files explicitly have the REF_COUNT and ALT_COUNT columns as refCount and altCount that you can use with ANEVA-DOT. 
These variant level files do not contain gene annotations, but those can be added using this script: https://github.com/wickdChromosome/variant_level_gene_annotation

Hope this helps!

**Comment by MariaEliana** [comment]
Hello @wickdChromosome ,
Thank you for the support. The new script works fine and we ran the data obteined with ANEVADOT!

**Comment by wickdChromosome** [comment]
Perfect, glad to hear things worked out.
